"""Users and Scopes

Revision ID: 09ac4f1dd6b6
Revises: 
Create Date: 2026-06-10 14:47:52.416973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '09ac4f1dd6b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scope_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время создания'),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время обновления'),
    sa.Column('delete_at', sa.DateTime(), nullable=True, comment='Время удаления'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время создания'),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время обновления'),
    sa.Column('delete_at', sa.DateTime(), nullable=True, comment='Время удаления'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Public user UUID'),
    sa.Column('first_name', sa.VARCHAR(length=500), nullable=False, comment='Имя'),
    sa.Column('last_name', sa.VARCHAR(length=500), nullable=True, comment='Фамилия'),
    sa.Column('middle_name', sa.VARCHAR(length=500), nullable=True, comment='Отчество'),
    sa.Column('email', sa.VARCHAR(length=500), nullable=False, comment='Почта'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активен ли'),
    sa.Column('hash_password', sa.CHAR(length=255), nullable=False, comment='Hash password'),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время создания'),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время обновления'),
    sa.Column('delete_at', sa.DateTime(), nullable=True, comment='Время удаления'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('scope_group_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время создания'),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время обновления'),
    sa.Column('delete_at', sa.DateTime(), nullable=True, comment='Время удаления'),
    sa.ForeignKeyConstraint(['group_id'], ['scope_groups.id'], ),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'scope_id', name='uq_group_scope'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True, comment='Кто выдал'),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время создания'),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время обновления'),
    sa.Column('delete_at', sa.DateTime(), nullable=True, comment='Время удаления'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id', 'scope_id', name='uq_user_scope')
    )
    op.create_index(op.f('ix_user_scopes_granted_by'), 'user_scopes', ['granted_by'], unique=False)
    op.create_index(op.f('ix_user_scopes_user_id'), 'user_scopes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_scopes_user_id'), table_name='user_scopes')
    op.drop_index(op.f('ix_user_scopes_granted_by'), table_name='user_scopes')
    op.drop_table('user_scopes')
    op.drop_table('scope_group_scopes')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('scopes')
    op.drop_table('scope_groups')
    # ### end Alembic commands ###
