"""Users fix pass

Revision ID: dee85c6c230d
Revises: 09ac4f1dd6b6
Create Date: 2026-06-10 16:07:55.410762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee85c6c230d'
down_revision: Union[str, Sequence[str], None] = '09ac4f1dd6b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'scope_group_scopes', ['id'])
    op.create_unique_constraint(None, 'scope_groups', ['id'])
    op.create_unique_constraint(None, 'scopes', ['id'])
    op.create_unique_constraint(None, 'user_scopes', ['id'])
    op.alter_column('users', 'hash_password',
               existing_type=sa.CHAR(length=255),
               type_=sa.VARCHAR(length=255),
               existing_comment='Hash password',
               existing_nullable=False)
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'hash_password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.CHAR(length=255),
               existing_comment='Hash password',
               existing_nullable=False)
    op.drop_constraint(None, 'user_scopes', type_='unique')
    op.drop_constraint(None, 'scopes', type_='unique')
    op.drop_constraint(None, 'scope_groups', type_='unique')
    op.drop_constraint(None, 'scope_group_scopes', type_='unique')
    # ### end Alembic commands ###
